version: '3.8'

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - foro-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/new_api?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Freya-100MTH

  frontend:
    build:
      context: ./foro-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - foro-network

networks:
  foro-network:
    driver: bridge