version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: foro_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Freya-100MTH
      MYSQL_DATABASE: new_api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - foro-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pFreya-100MTH"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./demo
      dockerfile: Dockerfile
    container_name: foro_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/new_api?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Freya-100MTH
    networks:
      - foro-network

  frontend:
    build: 
      context: ./foro-app
      dockerfile: Dockerfile
    container_name: foro_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - foro-network

networks:
  foro-network:
    driver: bridge

volumes:
  mysql_data: