version: '3.8'
services:
  backend:
    build: ./demo
    ports:
      - "8080:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - foro-network

  frontend:
    build: ./foro-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - foro-network

networks:
  foro-network:
    driver: bridge